DESCRIPTION = "Haddock is the standard tool for generating documentation from Haskell code."
SECTION = "devel"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM ?= "file://${COMMON_LICENSE_DIR}/BSD-3-Clause;md5=550794465ba0ec5312d6919e203a55f9"

SRC_URI = "https://github.com/haskell/${BPN}/archive/haddock-${PV}-release.zip"
SRC_URI[md5sum] = "fe75536741099d3c7d97d3fe1c8fe22a"
SRC_URI[sha256sum] = "457b579fa9c8868785ee88116c7af114aae4d07e62e363568178ed4963fcb1f0"
